[package]
name = "rusted_chrome"
version = "0.1.0"
publish = false
authors = ["Geir Sagberg <geir.sagberg@gmail.com>"]
edition = "2021"

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1

[profile.release]
lto = true
codegen-units = 1

[features]
default = [
    "bevy_asset_loader/stageless",
    "bevy_asset_loader/2d"
]

dev = [
    "bevy/dynamic",
]

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy" }
rand = "0.8.3"
bevy_asset_loader = { git = "https://github.com/geirsagberg/bevy_asset_loader", branch = "bevy_main" }
iyes_loopless = { git = "https://github.com/iyesgames/iyes_loopless", branch = "bevy_main" }

[target.'cfg(target_os = "linux")'.dependencies]
winit = { version = "0.27", features=["x11"] }

[build-dependencies]
embed-resource = "1.7"
